server:
  port: 80
  context-path: /wx
  tomcat:
    max-threads: 800
    accesslog:
      enabled: true
      rename-on-rotate: false
    uri-encoding: UTF-8
    redirect-context-root: false
logging:
  path: d:/springboot-tomcat-tmp/
debug: true # 测试
spring:
  application:
    admin:
      enabled: true # 是否启用admin特性，默认为: false
    name: wlrllr
  datasource:
    url: jdbc:mysql://192.168.200.229:3306/test?autoReconnect=true&amp;useUnicode=true&amp;characterEncoding=utf8
    username: root
    password: iaFaI8ZdB%#s
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  aop:
    auto: true
    proxy-target-class: true